### ISSUE TITLE
뭔가를 하기 전에 말로 하세요 쫌

### ISSUE THREAD

**Issue by hackmod** [ethereumsocial/go-esc#1]
.

**Comment by akx20000a** [comment]
@hackmod ㄴㄴ

**Comment by hackmod** [comment]
잘 개발할 역량 되시는 것 같은데 왜 하필 가즈아TV랑 붙어서 고생 사서 하시려 하실까요?
그냥 새 코인 만드세요.

**Comment by akx20000a** [comment]
@hackmod 열어드렸습니다^^

**Comment by akx20000a** [comment]
@hackmod  제 입장을 간략하게 적어서 올렸습니다 https://github.com/ethersocial/go-esc/pull/6
제목에 적으신것처럼 땡글이나 이더소셜과 연관지을 생각은 없고요, 계획하는 로드맵이나 목표도 다르고 해외 중심으로 나가려고 계획하고 있습니다. 깔끔하게 선채굴까지 해서 사기를 치거나 그럴수도 없고요.

**Comment by akx20000a** [comment]
개발자 입장으로서는 땡글에서 주는 보상이나 지원이 적어서 제가 아는 분하고 같이 분리 형식으로 해서 새 코인보다는 참여자의 참여 기회를 더 열어둔것 뿐입니다. 이 코인이 성공하게 되면 최대 수혜자는 코인을 가장 많이 가지신 쌍둥아빠님이나 땡글쪽이니 손해 볼 일도 없죠?

**Comment by akx20000a** [comment]
원하시는 답변이 아닐까 해서 올려봅니다 또 궁금하신 점 있으시면 답글 달아주세요.

**Comment by hackmod** [comment]
음 다시 열렸군요.
이미 제가 드릴 수 있는 조언은 온라인상에서 모두 말씀드렸습니다.
최종 판단은 스스로 알아서 하셔야 할 것 같습니다.

**Comment by eastcoinuser** [comment]
@hackmod 넵 알겠습니다.

**Comment by akx20000a** [comment]
@hackmod 거기까지만 해도 되는걸 사기라고 펌훼하시면 저희도 가만 안 있습니다. 하시는거 뭐든지 간에 저희가 당한거랑 똑같이 해드릴게요 😄 해킹당한 거래소가 하는 프로젝트가 뭐가 좋아서 졸졸 따라다니는지 모르겠지만요 자존심도 없으시나 ㅋㅋㅋㅋㅋ
